import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/app/nav/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Login Test",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="w-full xl:w-4/5 h-screen mx-auto
                        flex flex-col justify-start items-center">
            
            <Nav />
            <main className="w-full flex-grow flex flex-col items-center
                          overflow-y-auto">
              {children}
            </main>
      
            <footer className="w-full h-24 min-h-24 flex justify-center items-center
                             bg-gray-950 text-white text-lg">
              [부산대학교 K-Digital] AI 데이터 분석 풀스택 웹 개발자 양성과정
            </footer>
          </div>      
      </body>
    </html>
  );
}

